"""2

Revision ID: d5bf248979c4
Revises: 6262ac97e78c
Create Date: 2024-12-17 14:23:00.519677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bf248979c4'
down_revision: Union[str, None] = '6262ac97e78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drone_operations')
    op.add_column('operations', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operations', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'contract_id')
    op.create_table('drone_operations',
    sa.Column('drone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], name='drone_operations_drone_id_fkey'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name='drone_operations_operation_id_fkey'),
    sa.PrimaryKeyConstraint('drone_id', 'operation_id', name='drone_operations_pkey')
    )
    op.drop_table('maintenance_logs')
    # ### end Alembic commands ###
