"""1

Revision ID: efb98333ce15
Revises: 
Create Date: 2024-12-12 18:07:39.820633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb98333ce15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('RECONNAISSANCE', 'BOMBER', 'KAMIKAZE', 'MULTIFUNCTIONAL', name='drone_type'), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('drone_characteristics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Enum('MAX_FLIGHT_ALTITUDE', 'FLIGHT_RANGE', 'AUTONOMY_TIME', 'MAX_PAYLOAD', 'WEAPON_TYPE', 'CONTROL_SYSTEM', name='characteristic_key'), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('drone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drone_characteristics')
    op.drop_table('drones')
    # ### end Alembic commands ###
